export const respiratoryData = {
  datasets: {
    NNGYK: {
      name: "NNGYK (Hungary)",
      description: "Aggregated national respiratory virus surveillance shared by the National Public Health Center.",
    },
    ERVISS: {
      name: "ERVISS/ECDC (Europe)",
      description: "European Respiratory Virus Surveillance Summary consolidated by ECDC.",
    },
  },
  years: [2023, 2024, 2025],
  viruses: ["Influenza A", "Influenza B", "RSV", "SARS-CoV-2", "ILI (flu-like illness)"],
  weekly: [
    // Simplified synthetic sample data inspired by published seasonal curves.
    { dataset: "NNGYK", year: 2023, virus: "Influenza A", week: 40, cases: 210, region: "Central" },
    { dataset: "NNGYK", year: 2023, virus: "Influenza A", week: 44, cases: 560, region: "Central" },
    { dataset: "NNGYK", year: 2023, virus: "Influenza A", week: 48, cases: 1420, region: "Western" },
    { dataset: "NNGYK", year: 2023, virus: "Influenza A", week: 52, cases: 2890, region: "Eastern" },
    { dataset: "NNGYK", year: 2023, virus: "Influenza B", week: 50, cases: 640, region: "Central" },
    { dataset: "NNGYK", year: 2023, virus: "Influenza B", week: 52, cases: 1020, region: "Central" },
    { dataset: "NNGYK", year: 2023, virus: "RSV", week: 46, cases: 940, region: "Southern" },
    { dataset: "NNGYK", year: 2023, virus: "RSV", week: 48, cases: 760, region: "Southern" },
    { dataset: "NNGYK", year: 2024, virus: "Influenza A", week: 2, cases: 3100, region: "Central" },
    { dataset: "NNGYK", year: 2024, virus: "Influenza A", week: 4, cases: 3360, region: "Central" },
    { dataset: "NNGYK", year: 2024, virus: "Influenza B", week: 2, cases: 1290, region: "Western" },
    { dataset: "NNGYK", year: 2024, virus: "Influenza B", week: 4, cases: 1780, region: "Western" },
    { dataset: "NNGYK", year: 2024, virus: "RSV", week: 6, cases: 880, region: "Northern" },
    { dataset: "NNGYK", year: 2024, virus: "RSV", week: 8, cases: 640, region: "Northern" },
    { dataset: "NNGYK", year: 2024, virus: "SARS-CoV-2", week: 8, cases: 540, region: "Central" },
    { dataset: "NNGYK", year: 2024, virus: "SARS-CoV-2", week: 10, cases: 730, region: "Central" },
    // Flu-like illness consultations (NNGYK) — captured separately in weekly PDFs
    { dataset: "NNGYK", year: 2024, virus: "ILI (flu-like illness)", week: 40, cases: 1480, region: "National" },
    { dataset: "NNGYK", year: 2024, virus: "ILI (flu-like illness)", week: 44, cases: 2210, region: "National" },
    { dataset: "NNGYK", year: 2024, virus: "ILI (flu-like illness)", week: 48, cases: 4420, region: "National" },
    { dataset: "NNGYK", year: 2024, virus: "ILI (flu-like illness)", week: 52, cases: 7110, region: "National" },
    { dataset: "NNGYK", year: 2025, virus: "Influenza A", week: 2, cases: 3650, region: "Central" },
    { dataset: "NNGYK", year: 2025, virus: "Influenza A", week: 4, cases: 4120, region: "Central" },
    { dataset: "NNGYK", year: 2025, virus: "Influenza B", week: 2, cases: 1420, region: "Western" },
    { dataset: "NNGYK", year: 2025, virus: "Influenza B", week: 4, cases: 1980, region: "Western" },
    { dataset: "NNGYK", year: 2025, virus: "RSV", week: 6, cases: 720, region: "Northern" },
    { dataset: "NNGYK", year: 2025, virus: "RSV", week: 8, cases: 510, region: "Northern" },
    { dataset: "NNGYK", year: 2025, virus: "SARS-CoV-2", week: 6, cases: 680, region: "Central" },
    { dataset: "NNGYK", year: 2025, virus: "SARS-CoV-2", week: 8, cases: 910, region: "Central" },
    { dataset: "NNGYK", year: 2025, virus: "ILI (flu-like illness)", week: 2, cases: 6320, region: "National" },
    { dataset: "NNGYK", year: 2025, virus: "ILI (flu-like illness)", week: 4, cases: 8020, region: "National" },
    { dataset: "NNGYK", year: 2025, virus: "ILI (flu-like illness)", week: 6, cases: 8890, region: "National" },
    { dataset: "NNGYK", year: 2025, virus: "ILI (flu-like illness)", week: 8, cases: 10120, region: "National" },
    { dataset: "ERVISS", year: 2023, virus: "Influenza A", week: 40, cases: 490, region: "Baltic" },
    { dataset: "ERVISS", year: 2023, virus: "Influenza A", week: 52, cases: 2340, region: "Nordic" },
    { dataset: "ERVISS", year: 2023, virus: "RSV", week: 45, cases: 1140, region: "Iberia" },
    { dataset: "ERVISS", year: 2024, virus: "Influenza B", week: 4, cases: 880, region: "Central Europe" },
    { dataset: "ERVISS", year: 2024, virus: "Influenza A", week: 8, cases: 2670, region: "Central Europe" },
    { dataset: "ERVISS", year: 2024, virus: "SARS-CoV-2", week: 8, cases: 520, region: "Baltic" },
    { dataset: "ERVISS", year: 2024, virus: "SARS-CoV-2", week: 10, cases: 640, region: "Baltic" },
    { dataset: "ERVISS", year: 2025, virus: "Influenza A", week: 4, cases: 2980, region: "Central Europe" },
    { dataset: "ERVISS", year: 2025, virus: "Influenza B", week: 4, cases: 1240, region: "Central Europe" },
    { dataset: "ERVISS", year: 2025, virus: "RSV", week: 2, cases: 960, region: "Iberia" },
    { dataset: "ERVISS", year: 2025, virus: "RSV", week: 6, cases: 620, region: "Iberia" },
    { dataset: "ERVISS", year: 2025, virus: "SARS-CoV-2", week: 6, cases: 710, region: "Baltic" },
    { dataset: "ERVISS", year: 2025, virus: "SARS-CoV-2", week: 8, cases: 640, region: "Baltic" },
  ],
  variants: [
    {
      dataset: "NNGYK",
      year: 2024,
      virus: "SARS-CoV-2",
      breakdown: [
        { lineage: "JN.1", share: 42 },
        { lineage: "BA.2.86", share: 25 },
        { lineage: "XBB", share: 18 },
        { lineage: "Other", share: 15 },
      ],
    },
    {
      dataset: "NNGYK",
      year: 2024,
      virus: "Influenza A",
      breakdown: [
        { lineage: "H1N1pdm09", share: 58 },
        { lineage: "H3N2", share: 37 },
        { lineage: "Other", share: 5 },
      ],
    },
    {
      dataset: "ERVISS",
      year: 2024,
      virus: "Influenza B",
      breakdown: [
        { lineage: "Victoria", share: 62 },
        { lineage: "Yamagata", share: 28 },
        { lineage: "Other", share: 10 },
      ],
    },
  ],
};

export const europeanContextSample = {
  detections: [
    { virus: "Influenza A", week: "2025-W08", detections: 13210 },
    { virus: "Influenza B", week: "2025-W08", detections: 4880 },
    { virus: "RSV", week: "2025-W06", detections: 2210 },
    { virus: "SARS-CoV-2", week: "2025-W06", detections: 1750 },
  ],
  positivity: [
    { virus: "Influenza A/B", week: "2025-W08", positivity: 18.0, tests: 10120 },
    { virus: "RSV", week: "2025-W06", positivity: 8.9, tests: 2840 },
    { virus: "SARS-CoV-2", week: "2025-W06", positivity: 5.7, tests: 4620 },
  ],
};

export const europeanPositivityTrendSample = [
  // Influenza positivity across EU/EEA
  { virus: "Influenza A/B", week: "2024-W42", positivity: 6.2 },
  { virus: "Influenza A/B", week: "2024-W44", positivity: 7.8 },
  { virus: "Influenza A/B", week: "2024-W46", positivity: 9.1 },
  { virus: "Influenza A/B", week: "2024-W48", positivity: 11.5 },
  { virus: "Influenza A/B", week: "2024-W50", positivity: 13.6 },
  { virus: "Influenza A/B", week: "2025-W02", positivity: 15.9 },
  { virus: "Influenza A/B", week: "2025-W04", positivity: 17.2 },
  { virus: "Influenza A/B", week: "2025-W06", positivity: 18.0 },
  { virus: "Influenza A/B", week: "2025-W08", positivity: 16.7 },
  // RSV positivity trend
  { virus: "RSV", week: "2024-W44", positivity: 5.1 },
  { virus: "RSV", week: "2024-W48", positivity: 6.2 },
  { virus: "RSV", week: "2024-W50", positivity: 6.8 },
  { virus: "RSV", week: "2025-W02", positivity: 7.0 },
  { virus: "RSV", week: "2025-W04", positivity: 6.4 },
  { virus: "RSV", week: "2025-W06", positivity: 6.1 },
  // SARS-CoV-2 positivity trend
  { virus: "SARS-CoV-2", week: "2024-W42", positivity: 3.1 },
  { virus: "SARS-CoV-2", week: "2024-W46", positivity: 3.8 },
  { virus: "SARS-CoV-2", week: "2024-W48", positivity: 4.4 },
  { virus: "SARS-CoV-2", week: "2024-W50", positivity: 5.1 },
  { virus: "SARS-CoV-2", week: "2025-W02", positivity: 5.3 },
  { virus: "SARS-CoV-2", week: "2025-W04", positivity: 5.1 },
  { virus: "SARS-CoV-2", week: "2025-W06", positivity: 4.9 },
  { virus: "SARS-CoV-2", week: "2025-W08", positivity: 4.2 },
];
